### ISSUE TITLE
Possible sporadic failure

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/approval-api#22]
https://travis-ci.org/ManageIQ/approval-api/builds/457684560 shows a sporadic failure, but I cannot get it to fail locally no matter what I do.

From the spec, it is structured very strangely in that there is a top-level let for `template_id`, then a before block that uses the `template_id`, and then a context that sets a different `template_id`.  I'm wondering if that override is happening in a different order, but I'm not sure.

**Comment by Fryguy** [comment]
Failure line is https://github.com/ManageIQ/approval-api/blob/master/spec/requests/workflows_spec.rb#L34

**Comment by hsong-rh** [comment]
The issue was fixed by https://github.com/ManageIQ/approval-api/pull/21
